/* Archivo generado automáticamente. Edite MAESTRO_COLABORADORES.xlsx, no este archivo. */
window.ASYS_COLABORADORES_META = {
  "generatedAt": "2026-09-08T00:22:17",
  "source": "MAESTRO_COLABORADORES.xlsx",
  "total": 12
};
window.ASYS_COLABORADORES = [
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0001",
    "NOMBRE_COMPLETO": "ANDREA PRUEBA MORALES",
    "CORREO_COLABORADOR": "andrea.morales@example.invalid",
    "PUESTO": "Analista de Operaciones",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Operaciones",
    "FECHA_INGRESO": "2024-01-15T00:00:00",
    "SALARIO_BASE": 8500,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-001",
    "LIDER_NOMBRE": "LAURA DEMO REYES",
    "LIDER_CORREO": "laura.reyes@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-001",
    "ANALISTA_WF_NOMBRE": "WALTER DEMO PAZ",
    "ANALISTA_WF_CORREO": "walter.paz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0002",
    "NOMBRE_COMPLETO": "BRUNO EJEMPLO CASTILLO",
    "CORREO_COLABORADOR": "bruno.castillo@example.invalid",
    "PUESTO": "Asesor de Servicio",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Servicio al Cliente",
    "FECHA_INGRESO": "2022-08-08T00:00:00",
    "SALARIO_BASE": 6750,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-002",
    "LIDER_NOMBRE": "MARTA EJEMPLO LEON",
    "LIDER_CORREO": "marta.leon@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-001",
    "ANALISTA_WF_NOMBRE": "WALTER DEMO PAZ",
    "ANALISTA_WF_CORREO": "walter.paz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0003",
    "NOMBRE_COMPLETO": "CARLA FICTICIA LOPEZ",
    "CORREO_COLABORADOR": "carla.lopez@example.invalid",
    "PUESTO": "Coordinadora Administrativa",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Administracion",
    "FECHA_INGRESO": "2021-03-22T00:00:00",
    "SALARIO_BASE": 11200,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-003",
    "LIDER_NOMBRE": "RICARDO DEMO SOLIS",
    "LIDER_CORREO": "ricardo.solis@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-002",
    "ANALISTA_WF_NOMBRE": "WENDY DEMO CRUZ",
    "ANALISTA_WF_CORREO": "wendy.cruz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0004",
    "NOMBRE_COMPLETO": "DIEGO MUESTRA HERRERA",
    "CORREO_COLABORADOR": "diego.herrera@example.invalid",
    "PUESTO": "Supervisor de Calidad",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Calidad",
    "FECHA_INGRESO": "2020-11-02T00:00:00",
    "SALARIO_BASE": 14500,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-004",
    "LIDER_NOMBRE": "SOFIA MUESTRA VEGA",
    "LIDER_CORREO": "sofia.vega@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-002",
    "ANALISTA_WF_NOMBRE": "WENDY DEMO CRUZ",
    "ANALISTA_WF_CORREO": "wendy.cruz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0005",
    "NOMBRE_COMPLETO": "ELENA PRUEBA RAMIREZ",
    "CORREO_COLABORADOR": "elena.ramirez@example.invalid",
    "PUESTO": "Analista Financiera",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Finanzas",
    "FECHA_INGRESO": "2023-05-10T00:00:00",
    "SALARIO_BASE": 9800,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-005",
    "LIDER_NOMBRE": "MIGUEL PRUEBA ORTIZ",
    "LIDER_CORREO": "miguel.ortiz@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-003",
    "ANALISTA_WF_NOMBRE": "VALERIA DEMO PINEDA",
    "ANALISTA_WF_CORREO": "valeria.pineda@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-GT-0006",
    "NOMBRE_COMPLETO": "FABIAN EJEMPLO DIAZ",
    "CORREO_COLABORADOR": "fabian.diaz@example.invalid",
    "PUESTO": "Tecnico de Soporte",
    "PAIS_CODIGO": "GT",
    "PAIS_NOMBRE": "Guatemala",
    "EMPRESA": "CUENTAME",
    "DEPARTAMENTO": "Tecnologia",
    "FECHA_INGRESO": "2025-02-17T00:00:00",
    "SALARIO_BASE": 7200,
    "MONEDA": "GTQ",
    "LIDER_CODIGO": "LDR-GT-006",
    "LIDER_NOMBRE": "PAOLA EJEMPLO MENA",
    "LIDER_CORREO": "paola.mena@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-GT-003",
    "ANALISTA_WF_NOMBRE": "VALERIA DEMO PINEDA",
    "ANALISTA_WF_CORREO": "valeria.pineda@example.invalid",
    "ESTADO_COLABORADOR": "INACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0001",
    "NOMBRE_COMPLETO": "GABRIELA EJEMPLO SOLANO",
    "CORREO_COLABORADOR": "gabriela.solano@example.invalid",
    "PUESTO": "Ejecutiva de Servicio",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Servicio al Cliente",
    "FECHA_INGRESO": "2023-06-01T00:00:00",
    "SALARIO_BASE": 650000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-001",
    "LIDER_NOMBRE": "LUCIA EJEMPLO ROJAS",
    "LIDER_CORREO": "lucia.rojas@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-001",
    "ANALISTA_WF_NOMBRE": "WILLIAM EJEMPLO LEON",
    "ANALISTA_WF_CORREO": "william.leon@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0002",
    "NOMBRE_COMPLETO": "HECTOR MUESTRA VARGAS",
    "CORREO_COLABORADOR": "hector.vargas@example.invalid",
    "PUESTO": "Analista de Operaciones",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Operaciones",
    "FECHA_INGRESO": "2022-09-19T00:00:00",
    "SALARIO_BASE": 720000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-002",
    "LIDER_NOMBRE": "MARCO MUESTRA ARIAS",
    "LIDER_CORREO": "marco.arias@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-001",
    "ANALISTA_WF_NOMBRE": "WILLIAM EJEMPLO LEON",
    "ANALISTA_WF_CORREO": "william.leon@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0003",
    "NOMBRE_COMPLETO": "ISABEL PRUEBA MORA",
    "CORREO_COLABORADOR": "isabel.mora@example.invalid",
    "PUESTO": "Especialista de Calidad",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Calidad",
    "FECHA_INGRESO": "2021-07-12T00:00:00",
    "SALARIO_BASE": 810000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-003",
    "LIDER_NOMBRE": "PATRICIA PRUEBA SOTO",
    "LIDER_CORREO": "patricia.soto@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-002",
    "ANALISTA_WF_NOMBRE": "XIMENA DEMO CAMPOS",
    "ANALISTA_WF_CORREO": "ximena.campos@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0004",
    "NOMBRE_COMPLETO": "JORGE FICTICIO CHAVES",
    "CORREO_COLABORADOR": "jorge.chaves@example.invalid",
    "PUESTO": "Coordinador de Cuenta",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Operaciones",
    "FECHA_INGRESO": "2020-01-20T00:00:00",
    "SALARIO_BASE": 950000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-004",
    "LIDER_NOMBRE": "ALVARO DEMO VILLALOBOS",
    "LIDER_CORREO": "alvaro.villalobos@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-002",
    "ANALISTA_WF_NOMBRE": "XIMENA DEMO CAMPOS",
    "ANALISTA_WF_CORREO": "ximena.campos@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0005",
    "NOMBRE_COMPLETO": "KAREN DEMO MENDEZ",
    "CORREO_COLABORADOR": "karen.mendez@example.invalid",
    "PUESTO": "Analista de Nomina",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Recursos Humanos",
    "FECHA_INGRESO": "2024-04-04T00:00:00",
    "SALARIO_BASE": 780000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-005",
    "LIDER_NOMBRE": "DANIELA DEMO QUIROS",
    "LIDER_CORREO": "daniela.quiros@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-003",
    "ANALISTA_WF_NOMBRE": "YENDRY MUESTRA RUIZ",
    "ANALISTA_WF_CORREO": "yendry.ruiz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  },
  {
    "CODIGO_EMPLEADO": "DEMO-CR-0006",
    "NOMBRE_COMPLETO": "LEONARDO PRUEBA NUÑEZ",
    "CORREO_COLABORADOR": "leonardo.nunez@example.invalid",
    "PUESTO": "Desarrollador Junior",
    "PAIS_CODIGO": "CR",
    "PAIS_NOMBRE": "Costa Rica",
    "EMPRESA": "ASEGURO",
    "DEPARTAMENTO": "Tecnologia",
    "FECHA_INGRESO": "2025-01-06T00:00:00",
    "SALARIO_BASE": 880000,
    "MONEDA": "CRC",
    "LIDER_CODIGO": "LDR-CR-006",
    "LIDER_NOMBRE": "ESTEBAN PRUEBA ACUÑA",
    "LIDER_CORREO": "esteban.acuna@example.invalid",
    "ANALISTA_WF_CODIGO": "WF-CR-003",
    "ANALISTA_WF_NOMBRE": "YENDRY MUESTRA RUIZ",
    "ANALISTA_WF_CORREO": "yendry.ruiz@example.invalid",
    "ESTADO_COLABORADOR": "ACTIVO",
    "FECHA_ACTUALIZACION": "2026-09-07T08:00:00"
  }
];
